name: GH-Actions-Workflow
on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello World" 
      - name: Checking out code
        uses: actions/checkout@v4
      - name: Displaying the code
        run : ls -ltr
      


    
